import Image from 'next/image';
import type { Metadata } from 'next';
import { Inter, Orbitron } from 'next/font/google';
import { Links } from './links'; 
import { Providers } from './providers'; 
import { Heading, Button, IconButton, ButtonGroup } from '@chakra-ui/react'; 
import { SwitchModeButton, ThemeButton }  from './ThemeButton';
import HamburgerMenu from './HamburgerMenu';
import { ChakraProvider } from '@chakra-ui/react'; 
import { Stack, HStack, VStack } from '@chakra-ui/react'; 
import { useColorModeValue, ColorModeScript } from '@chakra-ui/react'; 
import theme from './theme'; 





const inter = Inter({ subsets: ['latin'], weight: ['300', '400', '500', '600'] })
const orbitron = Orbitron( { subsets: ['latin'], weight:['400', '500', '600']})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

function NavBar() { 
  // const buttonBg = useColorModeValue("black", "white"); 
  // const buttonColor = useColorModeValue("white", "black"); 

  return ( 
    <HStack p="3em" h="5em" gap={10} justify="space-between" align-items="center" pos="absolute" w="100%">
      <Heading fontWeight="semibold" fontSize={30}>TIMEBLOCKER</Heading> 
      <HStack gap={10} justify="space-between" align-items="center"> 
        <SwitchModeButton/> 
        <Button colorScheme="black" variant="outline">SYNC</Button>
        <ThemeButton>LOG IN</ThemeButton>
        <HamburgerMenu/> 
      </HStack>
    </HStack> 

  )
}
// function NavBar() { 
//   const LOGO_SCALE = 0.12; 
//   return ( 
//     <div id="navbar"> 
//       <Heading fontWeight='black'>TIMEBLOCKER</Heading> 
//       <div id="nav-right"> 
//         <SwitchModeButton/> 
//         <Button colorScheme="black" variant="outline">SYNC</Button>
//         <Button colorScheme="blackAlpha" variant="solid">LOG IN</Button>
//         <HamburgerMenu/> 
//       </div> 
//     </div> 
//   )
// }

{/* 
      </div> 

      {/* <Image id="logo" alt="logo-light" height={356 * LOGO_SCALE} width={1859 * LOGO_SCALE} src="/logos/logo-light.png"></Image>
      <h2> TIMEBLOCKER </h2>
      <div id="right-nav"> 
        <Links/> 
        <Button colorScheme='black' variant='outline'>SYNC</Button>
        <Button colorScheme='green' variant='solid'>LOG IN</Button> 
  </div>  */}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <main className={inter.className}> 
        <Providers> 
          <ColorModeScript initialColorMode={theme.config.initialColorMode} />
          <NavBar/> 
          {children}
        </Providers>
        </main> 
      </body>
    </html>
  )
}
